bg="#1D2024"
default_fg="#acbcc3"
session_fg="#EFC986"
session_selection_fg="#ffffff"
session_selection_bg="#30353b"
active_window_fg="#ffffff"
active_pane_border="#88ABDC"
mode_vi_selection_bg="#3e4452"
mode_vi_selection_fg="#C5C8D3"

# General status line
set -g status-style "fg=${default_fg},bg=${bg}"
set -g status-left-style "fg=${default_fg},bg=${bg}"
set -g status-right-style "fg=${default_fg},bg=${bg}"

set -g status-left-length 200
set -g status-right-length 200
set -g status-justify centre

# Left status
set -g status-left \
    "#[fg=${session_fg},bg=${bg}] #S#{?#{e|>:#{server_sessions},1}, (+#{e|-:#{server_sessions},1}),}"

# Windows list
set -g window-status-format \
    "#[fg=${default_fg},bg=${bg}]   #I:#W "

set -g window-status-current-format \
    "#[fg=${active_window_fg},bg=${bg}]  #I:#W#{?window_zoomed_flag,🔎,} "

set -g window-status-style \
    "fg=${default_fg},bg=${bg}"

set -g window-status-current-style \
    "fg=${active_window_fg},bg=${bg}"

set -g window-status-last-style \
    "fg=${default_fg},bg=${bg}"

set -g window-status-separator ""

# Right status
set -g @kbd-layout-format \
    "#[fg=yellow,bg=${bg}]#{value}#[fg=${default_fg},bg=${bg}]"

set -g status-right \
    "#[fg=#{?client_prefix,yellow,${bg}},bg=${bg}]▼#[fg=${default_fg},bg=${bg}] ⌨ #{kbd_layout} |  #{cpu -i 3} |  #{mem}"

# Prompt and window rename
set -g message-style \
    "fg=${default_fg},bg=${bg}"

set -g message-command-style \
    "fg=${default_fg},bg=${bg}"

# Copy mode
set -g mode-style \
    "fg=${mode_vi_selection_fg},bg=${mode_vi_selection_bg}"

# Pane borders
set -g pane-active-border-style \
    "fg=${active_pane_border},bg=default,bold"

set -g pane-border-style \
    "fg=brightblack,bg=default"

# which-key popup plugin
set -g @which-key-popup-bg "bg=${bg}"
